language: node_js
node_js:
  - "iojs"
  - "8"
  - "7"
  
sudo: false

os:
  - linux

env:
  global:
    - SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true

matrix:
  fast_finish: true
  exclude:
    - node_js: iojs
    - node_js: "0.10"
      os: osx
    - node_js: "0.12"
      os: osx

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CC="gcc-4.7";
      export CXX="g++-4.7";
      export LINK="gcc-4.7";
      export LINKXX="g++-4.7";
    fi
  - nvm --version
  - node --version
  - npm --version
  - gcc --version
  - g++ --version

script:
  - npm install
  - npm test
  - npm build

cache:
  directories:
    - node_modules
    - packages/create-react-app/node_modules
    - packages/react-scripts/node_modules